Document: android-compatible-env
Title: Debian android-compatible-env Manual
Author: <insert document author here>
Abstract: This manual describes what android-compatible-env is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/android-compatible-env/android-compatible-env.sgml.gz

Format: postscript
Files: /usr/share/doc/android-compatible-env/android-compatible-env.ps.gz

Format: text
Files: /usr/share/doc/android-compatible-env/android-compatible-env.text.gz

Format: HTML
Index: /usr/share/doc/android-compatible-env/html/index.html
Files: /usr/share/doc/android-compatible-env/html/*.html
